language: ruby

rvm:
  - 2.1
  - 2.1.5
  - 2.2.3
  - 2.3.0
  - ruby-head
  - rbx

os:
  - linux
  - osx

branches:
  only:
    - master
    - v0.10
    - v0.12
    - v0.14

gemfile:
  - Gemfile

script: bundle exec rake

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: 2.3.0
