language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.0
  - ruby-head
  - rbx-2

os:
  - linux
  - osx

branches:
  only:
    - master
    - v0.10
    - v0.14

gemfile:
  - Gemfile

script: bundle exec rake

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: 2.2.0
