version: '{build}'

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - IF %ridk%==0 "%devkit%\\devkitvars.bat"
  - ruby --version
  - gem --version
  - IF %ridk%==1 ridk.cmd exec bundle install
  - IF %ridk%==0 bundle install
build: off
test_script:
  - bundle exec rake test
#  - bundle exec rake test TESTOPTS=-v

branches:
  only:
    - master

# https://www.appveyor.com/docs/installed-software/#ruby
environment:
  matrix:
    - ruby_version: "25-x64"
      ridk: 1
    - ruby_version: "25"
      ridk: 1
    - ruby_version: "24-x64"
      ridk: 1
    - ruby_version: "24"
      ridk: 1
