name: "Mark or close stale issues and PRs"
on:
  schedule:
  - cron: "00 10 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 90
        days-before-close: 30
        stale-issue-message: "This issue has been automatically marked as stale because it has been open 90 days with no activity. Remove stale label or comment or this issue will be closed in 30 days"
        stale-pr-message: "This PR has been automatically marked as stale because it has been open 90 days with no activity. Remove stale label or comment or this PR will be closed in 30 days"
        close-issue-message: "This issue was automatically closed because of stale in 30 days"
        close-pr-message: "This PR was automatically closed because of stale in 30 days"
        stale-pr-label: "stale"
        stale-issue-label: "stale"
        exempt-issue-labels: "bug,enhancement,feature request,pending,work_in_progress,v1,v2"
        exempt-pr-labels: "bug,enhancement,feature request,pending,work_in_progress,v1,v2"
